# Generated by Django 4.2.7 on 2023-11-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
        migrations.RenameModel(
            old_name="SubSkills",
            new_name="SubSkill",
        ),
    ]
